version: '3'
services:
  client:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  server:
    build:
      context: ./answer_sheet_backend
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY = 93f9b1c66ebed8edb26c18a4af41f65c1f7131df0878a497460e39dbca2c69c7
      - MONGO_URI = mongodb+srv://ui20cs61:Sachet123@cluster0.pl1zog4.mongodb.net/?retryWrites=true&w=majority
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge